<a href="https://colab.research.google.com/github/gkadusumilli/Machinelearning/blob/master/Introduction_to_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Introduction to NumPy

-Gopalakrishna Adusumilli
gk1291@outlook.com

###Numpy Installation
1. Open command prompt(cmd)
2. Run *pip install numpy*.

![Importance of NumPy](https://cloudxlab.com/blog/wp-content/uploads/2017/12/numpypandasfeatureimage-3.png)

otherwise you can refer [NumPy website](https://numpy.org) and follow the instructions provided.

### Numpy Version 

In [0]:
import numpy
numpy . _version_

### List Creation- using Integers, Strings or creating Heterogeneous Lists

The standard mutable multi element contained in python is the **list** we can create a list of integers

In [2]:
A=list(range(10))
A


[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

Similarly a list of strings

In [3]:
A2=[str(c) for c in A]

A2

['0', '1', '2', '3', '4', '5', '6', '7', '8', '9']

In [4]:
type(A2[0])

str

We can create Heterogeneous lists

In [5]:
A3=[True, "2",3.0,4]

A3

[True, '2', 3.0, 4]

In [6]:
[type(item) for item in A3]

[bool, str, float, int]

### Array- One Dimensional, Two Dimensional

Python offers several diffrent options for storing data in efficient, fixed-type data buffers. The Built in array module can be used to create dense arrays of uniform type

In [7]:
import array 

A=list(range(10))
# 'i' is a type code indicating the contents are integers
A1=array.array('i',A)
A

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

we can use **np.array**  to create arrays from python lists

In [8]:
import numpy as np
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

if we want to explicitly set the data type of resulting array, we can use the **dtype** keyword

In [9]:
np.array([1,3,4,5,6],dtype='float32')

array([1., 3., 4., 5., 6.], dtype=float32)

Now we will work on initializing a multi dimensional array using a list of lists

In [10]:
np.array([range(i,i+3) for i in [2,4,6]])

# The inner lists are treated as rows of the resulting 2D array

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

Creating a length-10 integer array filled with zeros

In [11]:
np.zeros(10,dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

Creating a 3x4 floating point array filled with 1's

In [12]:
np.ones((3,4), dtype=float)

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

Create a 3x4 array filled with 3.14

In [13]:
np.full((3,4),3.14)

array([[3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14]])

Creating an array filled with linear sequence starting at 0, ending at 20, stepping by 2

syntax: **np.arange(start bit,last bit,step size)**

In [14]:
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

creating an array of five values evenly spaced between 0 to 1

In [15]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

creating an 3x3 arrayof uniformly distributed random values between 0&1

In [16]:
np.random.random((3,3))

array([[0.69847566, 0.47119672, 0.34411925],
       [0.10504705, 0.54087233, 0.55094563],
       [0.7174562 , 0.29184153, 0.08254161]])

Creating a 3x3 array of random integers in the interval [0,10]

In [17]:
np.random.randint(0,10,(3,3))

array([[8, 3, 3],
       [8, 4, 8],
       [5, 1, 6]])

Creating a 3x3 identity matrix

In [18]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

create an un initialized array of 3 integers. the values will be whatever happens to already exist at that memory location


In [19]:
np.empty(3)

array([1., 1., 1.])

## Basics of Numpy arrays

Categories of basic array manipulation are 
###1. Attributes of arrays 
   
   Determining the size, shape, memory consumption and data types of arrays

###2. Indexing of arrays

   Getting and setting the value of individual array elements

###3. Slicing of arrays

   Getting and setting smaller sub arrays within a larger array

###4. Joining and splitting of arrays

   Combining multiple arrays into one, and splitting one array into many


### 1. NumPy Array Attributes

In [0]:
np.random.seed(0) #seed for reproducibility

X1=np.random.randint(10,size=6) #1D array
X2=np.random.randint(10,size=(3,4)) #2D array
X3=np.random.randint(10,size=(3,4,5)) #3D array

Each array has attributes **ndim**(The number of dimensions), **shape**(Size of each dimension) **size**(total size of array), **itemsize**(list the size in bytes of each array element)

In [21]:
print("X3 ndim:",X3.ndim)
print("X3 shape:",X3.shape)
print("X3 size:",X3.size)
print("X3 dtype:",X3.dtype)
print("X3 itemsize:",X3.itemsize,"bytes")
print("nbytes:",X3.nbytes,"bytes")

X3 ndim: 3
X3 shape: (3, 4, 5)
X3 size: 60
X3 dtype: int64
X3 itemsize: 8 bytes
nbytes: 480 bytes


###2. Indexing of Arrays

In a 1D array, we can access ith value(Counting from Zero) by specifying index in square brackets, just as with python lists


In [22]:
X1

array([5, 0, 3, 3, 7, 9])

In [23]:
X1[0]

5

In [24]:
X1[4]

7

To index from the end of the array, you can use negative indices

In [25]:
X1[-1]

9

In [26]:
X1[-2]

7

For a multi dimensional array, you can access items using a Comma separated tuple of indices

In [27]:
X2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [28]:
X2[0,0]

3

In [29]:
X2[2,-1]

7

We can also modify values using any of the above index notation

In [30]:
X2[0,0]=15
X2

array([[15,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

### 3. Array Slicing: Accessing Sub arrays

The NumPy slicing syntax follows that of the standard python list; to access slice of an array X use this

**X[start:stop:step]**

if any of these are unspecified, the default to the values of start=0, stop=size of dimension, step=1

let us access subarrays in 1D and in multiple dimensions

#### One Dimensional Sub arrays

In [32]:
X=np.arange(10)
X

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [39]:
print(X[:5]) #prints first five elements

print(X[5:]) #elements after index 5

print(X[4:7]) #middle subarray

print(X[::3]) #every 3rd element

print(X[1::2]) # every other element starting at index 1

[0 1 2 3 4]
[5 6 7 8 9]
[4 5 6]
[0 3 6 9]
[1 3 5 7 9]


When **step value** is negative in this case, the defaults for start and stop are swapped. this becomes a convineant way to reverse an array

In [40]:
print(X[::-1]) #all elements, reversed

print(X[5::-2]) #reversed every other from index 5

[9 8 7 6 5 4 3 2 1 0]
[5 3 1]


#### Multi Dimensional subarrays

Multi dimensional slices works in the same way, with multiple slices separated by commas

In [41]:
X2

print(X2[:2,:3]) #two rows, three coloumns

print(X2[:3,::2]) #all rows, every other coloumn



[[15  5  2]
 [ 7  6  8]]
[[15  2]
 [ 7  8]
 [ 1  7]]


Subarray dimensions can even be reversed toghether

In [42]:
X2[::-1,::-1]

array([[ 7,  7,  6,  1],
       [ 8,  8,  6,  7],
       [ 4,  2,  5, 15]])

#### Acessing Rows and Coloumns

One commonly needed routine is accessing single rows or coloumns of an array. you can do this by combining indexing and slicing, using an empty slice marked by single colon(:)

In [43]:
print(X2[:,0]) # first coloumn of X2

[15  7  1]


In [44]:
print(X2[0,:]) # first row of X2

[15  5  2  4]


in case of row access, the empty slice can be omitted for more compact syntax

In [45]:
print(X2[0]) #equivalent to X2[0,:]

[15  5  2  4]


#### Sub arrays as no-copy views

In [46]:
print(X2)

[[15  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]


let us extract a 2x2 sub array from this

In [47]:
X2_sub=X2[:2,:2]
print(X2_sub)

[[15  5]
 [ 7  6]]


Now if we modify this sub array, we will see that original array is changed! observe

In [48]:
X2_sub[0,0]=99
print(X2_sub)

[[99  5]
 [ 7  6]]


In [49]:
print([X2])

[array([[99,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])]


####creating copy of arrays

In [50]:
X2_sub_copy=X2[:2,:2].copy()
print(X2_sub_copy)

[[99  5]
 [ 7  6]]


if we now modify this sub array, the original array is not touched

In [51]:
X2_sub_copy[0,0]=42
print(X2_sub_copy)

[[42  5]
 [ 7  6]]


In [52]:
print(X2)

[[99  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]


####Reshaping of arrays

for example, if we want to put the numbers 1 through 9 in a 3x3 grid, you can do the following

In [53]:
grid=np.arange(1,10).reshape((3,3))
print(grid)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [54]:
x=np.array([1,3,3])

#row vector via reshape
x.reshape((1,3))

array([[1, 3, 3]])

In [55]:
#row vector via newaxis
x[np.newaxis,:]

array([[1, 3, 3]])

In [56]:
#column vector via reshape
x.reshape((3,1))

array([[1],
       [3],
       [3]])

In [57]:
#column vector via newaxis
x[:,np.newaxis]

array([[1],
       [3],
       [3]])

###4. Array Concatenation and Splitting

you might have noticed that above code worked on single arrays. it is also possible to combine multiple arrays into one, and to conversly split a single array into multiple arrays

#### Concatenation of Arrays
Concatenation, or joining of two arrays in NumPy, is primarily accomplished using the routines **np.concatenate**, **np.vstack** and **np.hstack**, **np.concatenate** takes a tuple or list of arrays as its first argument 

In [58]:
x=np.array([1,3,4])
y=np.array([3,2,1])
np.concatenate([x,y])

array([1, 3, 4, 3, 2, 1])

we can concatenate more than two arrays at once


In [59]:
z=[99,99,99]

print(np.concatenate([x,y,z]))

[ 1  3  4  3  2  1 99 99 99]


it can also be used for 2D arrays

In [0]:
grid=np.array([[1,2,3],[4,5,6]])

In [62]:
#concatenate along the first axis
np.concatenate([grid,grid])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [63]:
#Concatenate along the second axis (zero-indexed)

np.concatenate([grid,grid],axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

**np.vstack**: Vertical stack

**np.hstack**: Horizontal srack

In [64]:
x=np.array([1,2,3])

grid=np.array([[9,8,5],[4,5,6]])

#vertically stack the arrays
np.vstack([x,grid])

array([[1, 2, 3],
       [9, 8, 5],
       [4, 5, 6]])

In [65]:
#horizontally stack the arrays

y=np.array([[99],[99]])

np.hstack([grid,y])

array([[ 9,  8,  5, 99],
       [ 4,  5,  6, 99]])

#### Splitting of arrays

antonym of concatenation is splitting, which is implemented by functions **np.split**, **np.hsplit** and **np.vsplit**

In [68]:
x=[1,2,3,56,67,78,99,4,5,6]
x1,x2,x3=np.split(x,[3,6])
print(x1,x2,x3)

[1 2 3] [56 67 78] [99  4  5  6]


In [70]:
grid=np.arange(16).reshape((4,4))
grid

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [71]:
upper,lower=np.vsplit(grid,[2])

print(upper)
print(lower)

[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]
 [12 13 14 15]]


In [72]:
left,right=np.hsplit(grid,[2])
print(left)
print(right)

[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]
