<a href="https://colab.research.google.com/github/gkadusumilli/Machinelearning/blob/master/python_programming.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Introduction to Python Programming (Part-1)**

-Gopalakrishna Adusumilli gk1291@outlook.com

This worksheet will assist you to walkthrough the basic concepts of python
1. Reasons why python is a great choice for professionals ?
1. Variable & Type
2. Functions
3. Control
4. Built-in data structures

#**Reasons why Python is a Great Choice for Professionals**

1. **Python is a High-Level Programming Language**

A high-level programming language is one that abstracts away many of the details of the inner workings of the computer. A good example is memory management. Lower-level programming languages require a detailed understanding of the complexities of how computer’s memory is laid out, allocated and released, in addition to the time spent and lines of code required to handle tasks. Python abstracts away and handles many of these details automatically.

2. **It is Concise**

Python language, the code is more concise and entirely focussed on the logic of what you want to achieve.

For example, Python doesn’t require the use of curly braces or semicolons to delineate functions, loops, and lines the way many other languages do, which makes it more concise and, as some argue, improves readability.

3. **Easy to learn and Understand**

One observation that has influenced language in python is that programs are read more often than they are written. Python excels here as its code looks very close to plain English.

4. **Suitable for Rapid, Iterative Development**

Python is ideal for prototyping and rapid, iterative development because of interactive interpreter tools such as the Python shell, IPython, and Jupyter notebooks. In these interactive environments, you can write and execute each line of code in isolation and see the results immediately. Other languages have this too but in most cases not the same degree as python.

5. **Can be used Both for Prototyping and Production Code**

In addition to being great for prototyping, Python is also an excellent and powerful language for large production applications. Some of the largest software companies in the world make heavy use of Python in a variety of applications and use cases.

6. **The Python Standard Library**

Everything needed for basic operations is built right into the language, but in addition to that, the Python standard library has tools for working with files, media, networking, date and time information, and much more.

7. **Python Is Free!!!**

Python is developed under an open-source license making it free also for commercial use. 

Let us understand the concepts by writing a script to create a simple calculator.

In [0]:
2+4

6

In [0]:
2*3+5

11

In [0]:
log(3)

NameError: ignored

From the code snippet above, errors are raised when we call **log(2)** . the -**log** function don't exist in current python environment.

**log** function are defined in math module in python.

In [0]:
from math import log

#log(2) value will be returned as the log function is invoked

log(2)

0.6931471805599453

#**Variable & Type**

In this section we will assign variable to the values.

Variables in Python can **hold values of any type** (it may be int, char, string)

Variables**need not to be declared**, just assign a value to the variable.



####**Declaration of a variable**

In [0]:
a=2
b=5.0
x='hello world'

In [0]:
print(a)
print(b)
x

2
5.0


'hello world'

In [0]:
e=a*2+b
print(e)

9.0


####**Type**

we have defined 4 diffrent variables, we can utilize the function **type()** in Python

In [0]:
type(x)

type(e)

float

#**Functions**

A function is a block of code which performs a specific task. A major **purpose** of wrapping a chunk of code into a **function is to reuse the code**when needed

In [0]:

def fun(x):
  return x*x
fun(5)


25

Here we have defined **fun()** . This function takes **x** as input and returns the square of **x**.

we simply type the function name followed by the argument inside a pair of parenthesis. you can **notice** that **input or output are not required to define a function**

Python codes are structured with **indentation**. Each logical line of python code belongs to certain group.

another example defining a function to perform log operation.

In [0]:
from math import log
def log_fun(x,base=2):
  return log(x,base)

print(log_fun(5,2))


2.321928094887362


#**Control flows**

1. if/else
2. for loop
3. while loop
4. Break/Continue

##if/else

let's define a function to return the absolute value of input.

In [0]:
def fun2(x):
  if x>=0:
    return x
  else:
    return -x


In [0]:
fun2(2.5)

2.5

we can also put **if** after **else**. But in python, we use **elif** as a shortcut.

In [0]:
def fun3(x):
  if x==0:
    print('zero')
  elif x>0:
    print('positive')
  else:
    print('negative')

In [0]:
fun3(0)

zero


In [0]:
fun3(1)

positive


In [0]:
fun3(-1)

negative


##for loop

we use range to define the the set of values to be displayed. 

**range()** can take three arguments i.e range(start,stop,step). 

usually **range** is used to iterate sequence type.


In [0]:
for i in range(1,4):
  print(i)

1
2
3


In [0]:
type(range(1,4))

range

##While loop

In [0]:
i=1
while i<=5:
  print(i)
  i+=1

1
2
3
4
5


**i+=1** to add 1 to **i**, 

##Break/continue

Break/continue helps if we want to break the for/while loop earlier, or to skip a specific iteration.
The difference between **break** and **continue** is that calling 



*   **break** would exit the innermost 
loop (when there are nested loops, only the innermost loop is affected)
*   **continue** would just skip the current iteration and continue the loop if not finished.







In [0]:
for i in range(1,4):
  print(i)

  if i==1:
    break


1


In [0]:
for i in range(1,4):
  if i==2:
    continue
print(i)

3


# **Built-in Data Structures**

##List
A vector is a sequence of elements with the same type. In python, we can use **[]** to create a list, which is also a sequence of elements. But the elements in a list don't need to have the same type.
we use the function **length()**; and to get the number of elements in  a list in python

In [0]:
x=[1,2,5,6]
y=['hello','world','!']

In [0]:
print(x)

print(y)

[1, 2, 5, 6]
['hello', 'world', '!']


In [0]:
len(x)

4

In [0]:
z=[1,'hello']

print(z)

[1, 'hello']


To **access the specific element** from a vector or list, we could use []. sequence types in python are indexed beginning with the zero subscript.

In [0]:
x=[1,2,5,6]

x[1]

2

In [0]:
x[0]

1

In python, negative index number means indexing from the end of the list. Thus, **x[-1]** points to the last element and **x[-2]** points to the second last element of the list.

In [0]:
x=[1,2,5,6]

x[-1]

6

In [0]:
x[-2]

5

There is one interesting fact that we can add a **None** to a list in python

In [0]:
x=[1,None]
print(x)

print(len(x))

[1, None]
2


Sometimes we want to create a vector/list with the replicated elements.

for example, a vector/list with all elements equal to 0.

In [0]:
x=[0]*10

print(x)

y=[0,1]*5

print(y)

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 1, 0, 1, 0, 1, 0, 1, 0, 1]


when we use * operator to make replicates of a list, there is one caveat-if the element inside the list is mutable then the replicated elements point to the same memory adress. as a consequence, if one element is mutated other elements are also affected

In [0]:
x=[0] #x is a list which is mutable

y=[x]*5 #each element in y points to x

print(y)

y[2]=2 #we point y[2] to 2 but x is not mutated

print(y)

[[0], [0], [0], [0], [0]]
[[0], [0], 2, [0], [0]]


In [0]:
y[1][0]=-1

print(y)

[[-1], [-1], 2, [-1], [-1]]


#Slicing

Beside accessing a specific element from a vector/list, we may also need to do slicing, i.e., to select a subset of the vector/list.

There are two basic approaches of slicing

1. Integer based
2. Condition based

###1. Integer based

In [0]:
x=[1,2,3,4,5,6]

x[1:4]

[2, 3, 4]

In [0]:
x[0:5:2] # x[start:end:step]

[1, 3, 5]

###2. Condition Based

Condition-based slicing means to select a subset of the elements which satisfy certain condiotions.

let's create a list of sqaures of another list

In [0]:
x=[1,2,3,4,5,6]

[e for e in x if e%2==1] # % is the modulo operator in python

[1, 3, 5]

it is also common to use **if/else** with list comprehension to acheive more complex operations.

for example, given a list x, let's create a new list y so that non-negative elements in x are squared and the negative elemetns are replaced by 0's

In [0]:
x=[1,-1,0,2,5,-3]

[e**2 if e>=0 else 0 for e in x]

[1, 0, 0, 4, 25, 0]

#**Mutable and Immutable list** 

##Mutable List

As list structure in python is **mutable**, there are many things we can do with list!

In [0]:
x=[1,2,3]

x.append(4)

print(x)

[1, 2, 3, 4]


In [0]:
y=[5,6]
x.extend(y) #extend list y to x
x

[1, 2, 3, 4, 5, 6]

In [0]:
last=x.pop() #pop the last element from x

last

6

##*Immutable List*

Is there are any immutable data structure in python ? yes, for example tuple is immutable, which contains a sequence of elements.

In [0]:
x=(1,2,3,) #use () to create a tuple in python, it is adviced to always put a comma in end

type(x)

tuple

In [0]:
len(x)

3

In [0]:
x[0]

1

**Inference from the Mutable and Immutable list**

A mutable object can be changed after it is created, but an immutable object can't.


---



if we change the value of an element in a vector 
without changing the type of the element, the vector is mutable. 



---
if we change the value of an element to another type, the behavior of vector is immutable.



---





a variable itself is a reference or pointer to an object (usually stored in the machine's memory).

**To check the mutability of a variable, we can trace the memory address.**

In [0]:
x=list(range(1,1001)) #list() convert a range object to a list

x[0]=1.0 #from integer to float

print(hex(id(x)))

0x7f38541dfe88


#**Array**

Array is one of the most important data structures in mathematical and scientific programing.

we can use list as array in python, but lots of linear algebra operations are not supported for the list type. hence we can use a python package **numpy** 

In [0]:
import numpy as np

array1=np.reshape(list(range(1,13)),(4,3)) #convert a list to a 2d np.array

array1

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [0]:
type(array1)

numpy.ndarray

In [0]:
array2=np.reshape(list(range(1,7)),(3,2))

array2

array([[1, 2],
       [3, 4],
       [5, 6]])

In [0]:
array3=np.dot(array1,array2) #matrix multiplication using np.dot()

array3

array([[ 22,  28],
       [ 49,  64],
       [ 76, 100],
       [103, 136]])

In [0]:
array3.shape #get the shape(dimension) of array3

(4, 2)

In [0]:
array2=np.reshape(list(range(1,7)),(2,3)).T #use .T to transpose an array

array2

array([[1, 4],
       [2, 5],
       [3, 6]])

#**Dictionary**

Python comes with a variety of built-in data structures, capable of storing different types of data. A python dictionary is one such data structure that can store data in the form of key-value pairs. The values in Python dictionary can be accessed using the keys.

In [0]:
x={'a':1,'b':2}

x

{'a': 1, 'b': 2}

In [0]:
x['b']

2

In [0]:
len(x) #number of key:value pairs

2

In [0]:
x.pop('a') #remove the key 'a' and we get its value 1


1

In [0]:
x

{'b': 2}

#**data.frame**

preliminary let us understand **why data.frame ?** in other words why can't we just use vector, list, array/matrix and dictionary for all data manipulation tasks.

data.frame is must have feature for most of ETL (Extraction, transformation and load) operations. But data.frame provides a very intuitive way for us to understand the structured dataset.

a data.frame is usually flat with 2 dimensions, i.e row and column. the row dimension is across multiple observations and the column dimensions is across multiple attributes/features.

In [0]:
import pandas as pd

employee_df=pd.DataFrame({'name':['A','B','C'],'department':["Engineering","operations","sales"]})

employee_df

name   department
0    A  Engineering
1    B   operations
2    C        sales